// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/taylankasap/message-sender/api (interfaces: DBInterface)
//
// Generated by this command:
//
//	mockgen --package=api --destination=mock_db_interface.go . DBInterface
//

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	model "github.com/taylankasap/message-sender/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDBInterface is a mock of DBInterface interface.
type MockDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDBInterfaceMockRecorder
	isgomock struct{}
}

// MockDBInterfaceMockRecorder is the mock recorder for MockDBInterface.
type MockDBInterfaceMockRecorder struct {
	mock *MockDBInterface
}

// NewMockDBInterface creates a new mock instance.
func NewMockDBInterface(ctrl *gomock.Controller) *MockDBInterface {
	mock := &MockDBInterface{ctrl: ctrl}
	mock.recorder = &MockDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBInterface) EXPECT() *MockDBInterfaceMockRecorder {
	return m.recorder
}

// FetchSentMessages mocks base method.
func (m *MockDBInterface) FetchSentMessages() ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSentMessages")
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchSentMessages indicates an expected call of FetchSentMessages.
func (mr *MockDBInterfaceMockRecorder) FetchSentMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSentMessages", reflect.TypeOf((*MockDBInterface)(nil).FetchSentMessages))
}
